// layout.tsx

import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollClientWrapper from "./scroll-wrapper";
import { Viewport } from "next"; // Hoặc custom function

export const viewport: Viewport = {
  themeColor: "#your-primary-color", // Di chuyển vào đây
  colorScheme: "light", // Các prop khác: width, initialScale, etc.
};

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AskThemAll AI",
  description: "Generated by create next app",
  // Theme color được quản lý bởi Next.js
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="vi" className="min-h-dvh overflow-x-hidden">
        {/* Next.js sẽ tự động tạo thẻ <head> với metadata ở trên */}
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ScrollClientWrapper />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
